import fsp from "node:fs/promises";
import path from "node:path";
import type { Logger } from "../shared/logger.js";
import {
  BaseMediaService,
  CORS_HEADERS,
  HttpError,
  requireMethod,
  requireNumber,
  requireString,
  sendJson,
  sendNotFound,
  type RouteContext,
  type RouteTable,
  type ServiceSettings,
} from "../shared/service-http.js";
import type { BluetoothConfig } from "./config.js";
import { logger as defaultLogger } from "./logger.js";
import { PhoneManager, type PhoneAction } from "./phone.js";
import type { CallAction } from "./calls.js";
import type {
  BluetoothMedia,
  BluetoothPairing,
  BluetoothPlaybackAction,
  BluetoothState,
} from "./types.js";

const PLAYBACK_ACTIONS = ["play", "pause", "toggle", "next", "previous", "stop"] as const;
const PHONE_ACTIONS: PhoneAction[] = ["connect", "disconnect", "forget", "trust", "untrust"];
const SCAN_ACTIONS = ["start", "stop", "refresh"] as const;
const PAIRING_ACTIONS = ["pair", "confirm", "reject", "cancel", "submit"] as const;
const CALL_ACTIONS: CallAction[] = [
  "answer",
  "hangup",
  "reject",
  "dial",
  "mute",
  "unmute",
  "hold",
  "resume",
];

/** Cover-art file names are generated by us; anything else is rejected. */
const ARTWORK_NAME = /^[A-Za-z0-9_-]+\.jpg$/;

export interface BluetoothServiceOptions {
  logger?: Logger;
  settings?: Partial<ServiceSettings>;
  installProcessHandlers?: boolean;
  /** Injected for tests; defaults to a real BlueZ-backed manager. */
  manager?: PhoneManager;
}

/**
 * Bluetooth source: BlueZ (D-Bus) bridge + HTTP/SSE API.
 *
 * The class is intentionally thin. All of the Bluetooth behaviour lives in
 * {@link PhoneManager}, which publishes one device-centric state tree; this
 * layer only maps HTTP routes onto its verbs and serves the cover-art cache.
 * BlueZ is never torn down on suspend, because a phone must stay visible for
 * pairing and (later) calls.
 */
export class BluetoothService extends BaseMediaService<BluetoothState> {
  private readonly manager: PhoneManager;
  private readonly artworkDir: string;

  constructor(config: BluetoothConfig, options: BluetoothServiceOptions = {}) {
    super({
      name: "bluetooth",
      port: config.port,
      logger: options.logger ?? defaultLogger,
      settings: options.settings,
      installProcessHandlers: options.installProcessHandlers,
      logRequests: true,
    });

    this.artworkDir = config.artworkDir;
    this.manager =
      options.manager ??
      new PhoneManager({ config, logger: options.logger ?? defaultLogger });
    this.manager.on("state", () => this.broadcast());
  }

  /* ------------------------------- base hooks ----------------------------- */

  protected getState(): BluetoothState {
    return this.manager.getState();
  }

  protected async onStart(): Promise<void> {
    await this.manager.start();
  }

  protected async onStop(): Promise<void> {
    await this.manager.stop();
  }

  protected async onSuspend(): Promise<void> {
    await this.manager.suspend();
  }

  protected async onResume(): Promise<void> {
    await this.manager.resume();
  }

  protected isBusy(): boolean {
    return this.manager.isBusy();
  }

  protected healthDetails(): Record<string, unknown> {
    return this.manager.healthDetails();
  }

  protected createRoutes(): RouteTable {
    return {
      playback: (ctx) => this.handlePlayback(ctx),
      volume: (ctx) => this.handleVolume(ctx),
      artwork: (ctx) => this.handleArtwork(ctx),
      scan: (ctx) => this.handleScan(ctx),
      phone: (ctx) => this.handlePhone(ctx),
      pairing: (ctx) => this.handlePairing(ctx),
      calls: (ctx) => this.handleCalls(ctx),
    };
  }

  /* -------------------------------- handlers ------------------------------ */

  private async handlePlayback(ctx: RouteContext): Promise<void> {
    requireMethod(ctx, "POST");
    const action = requireString((await ctx.body()).action, "action");
    if (!PLAYBACK_ACTIONS.includes(action as BluetoothPlaybackAction)) {
      throw new HttpError(400, "Unknown playback action");
    }
    const media: BluetoothMedia = await this.manager.playback(action as BluetoothPlaybackAction);
    sendJson(ctx.res, 200, media);
  }

  private async handleVolume(ctx: RouteContext): Promise<void> {
    requireMethod(ctx, "POST");
    await this.manager.setVolume(requireNumber((await ctx.body()).volume, "volume"));
    sendJson(ctx.res, 200, this.getState());
  }

  /** `POST /api/scan` — `{ action: "start" | "stop" | "refresh" }`. */
  private async handleScan(ctx: RouteContext): Promise<void> {
    requireMethod(ctx, "POST");
    const action = requireString((await ctx.body()).action, "action");
    if (!SCAN_ACTIONS.includes(action as (typeof SCAN_ACTIONS)[number])) {
      throw new HttpError(400, "Unknown scan action");
    }
    sendJson(ctx.res, 200, await this.manager.scanAction(action));
  }

  /**
   * `POST /api/phone` — `{ action, deviceId }` where `action` is one of
   * `connect` (pairs when needed), `disconnect`, `forget`, `trust`, `untrust`.
   */
  private async handlePhone(ctx: RouteContext): Promise<void> {
    requireMethod(ctx, "POST");
    const body = await ctx.body();
    const action = requireString(body.action, "action");
    if (!PHONE_ACTIONS.includes(action as PhoneAction)) {
      throw new HttpError(400, "Unknown phone action");
    }
    const deviceId = requireString(body.deviceId, "deviceId");
    sendJson(ctx.res, 200, await this.manager.phoneAction(action, deviceId));
  }

  /**
   * `POST /api/pairing` — `{ action, deviceId?, value? }`.
   *
   * `confirm`/`reject` answer the prompt currently shown by the UI; `submit`
   * carries the digits of a passkey/PIN prompt.
   */
  private async handlePairing(ctx: RouteContext): Promise<void> {
    requireMethod(ctx, "POST");
    const body = await ctx.body();
    const action = requireString(body.action, "action");
    if (!PAIRING_ACTIONS.includes(action as (typeof PAIRING_ACTIONS)[number])) {
      throw new HttpError(400, "Unknown pairing action");
    }
    const deviceId = typeof body.deviceId === "string" ? body.deviceId : undefined;
    const value = typeof body.value === "string" ? body.value : undefined;
    const pairing: BluetoothPairing = await this.manager.pairingAction(action, deviceId, value);
    sendJson(ctx.res, 200, pairing);
  }

  /**
   * `POST /api/calls` — reserved for hands-free telephony. Answers 501 until
   * an HFP backend is installed, so the renderer can feature-detect instead of
   * discovering the gap by hitting a 404.
   */
  private async handleCalls(ctx: RouteContext): Promise<void> {
    requireMethod(ctx, "POST");
    const body = await ctx.body();
    const action = requireString(body.action, "action");
    if (!CALL_ACTIONS.includes(action as CallAction)) {
      throw new HttpError(400, "Unknown call action");
    }
    const number = typeof body.number === "string" ? body.number : undefined;
    const callId = typeof body.callId === "string" ? body.callId : undefined;
    await this.manager.callAction({ action: action as CallAction, number, callId });
    sendJson(ctx.res, 200, this.getState());
  }

  private async handleArtwork(ctx: RouteContext): Promise<void> {
    requireMethod(ctx, "GET");
    const name = ctx.parts[2] ?? "";
    if (!ARTWORK_NAME.test(name)) {
      sendNotFound(ctx.res);
      return;
    }

    try {
      const data = await fsp.readFile(path.join(this.artworkDir, name));
      ctx.res.writeHead(200, {
        "Content-Type": "image/jpeg",
        "Content-Length": data.length,
        "Cache-Control": "max-age=86400",
        ...CORS_HEADERS,
      });
      ctx.res.end(data);
    } catch {
      sendNotFound(ctx.res);
    }
  }
}
