/**
 * @file grand_modus.h
 *
 * @brief This header file was generated by cantools version 41.4.1 Wed Jun  3
 * 11:23:00 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef GRAND_MODUS_H
#define GRAND_MODUS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifndef EINVAL
#define EINVAL 22
#endif

/* Frame ids. */
#define GRAND_MODUS_ENGINE_FRAME_ID (0x181u)
#define GRAND_MODUS_GEARBOX_FRAME_ID (0x215u)
#define GRAND_MODUS_CLIMATE_FRAME_ID (0x374u)
#define GRAND_MODUS_BRAKES_FRAME_ID (0x5c5u)
#define GRAND_MODUS_LIGHTS_AND_DOORS_FRAME_ID (0x60du)
#define GRAND_MODUS_SAFETY_FRAME_ID (0x651u)

/* Frame lengths in bytes. */
#define GRAND_MODUS_ENGINE_LENGTH (8u)
#define GRAND_MODUS_GEARBOX_LENGTH (6u)
#define GRAND_MODUS_CLIMATE_LENGTH (3u)
#define GRAND_MODUS_BRAKES_LENGTH (8u)
#define GRAND_MODUS_LIGHTS_AND_DOORS_LENGTH (8u)
#define GRAND_MODUS_SAFETY_LENGTH (2u)

/* Extended or standard frame types. */
#define GRAND_MODUS_ENGINE_IS_EXTENDED (0)
#define GRAND_MODUS_GEARBOX_IS_EXTENDED (0)
#define GRAND_MODUS_CLIMATE_IS_EXTENDED (0)
#define GRAND_MODUS_BRAKES_IS_EXTENDED (0)
#define GRAND_MODUS_LIGHTS_AND_DOORS_IS_EXTENDED (0)
#define GRAND_MODUS_SAFETY_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */

/* Signal choices. */

/* Frame Names. */
#define GRAND_MODUS_ENGINE_NAME "ENGINE"
#define GRAND_MODUS_GEARBOX_NAME "GEARBOX"
#define GRAND_MODUS_CLIMATE_NAME "CLIMATE"
#define GRAND_MODUS_BRAKES_NAME "BRAKES"
#define GRAND_MODUS_LIGHTS_AND_DOORS_NAME "LIGHTS_AND_DOORS"
#define GRAND_MODUS_SAFETY_NAME "SAFETY"

/* Signal Names. */
#define GRAND_MODUS_ENGINE_ENGINE_RPM_NAME "ENGINE_RPM"
#define GRAND_MODUS_GEARBOX_REVERSE_GEAR_NAME "REVERSE_GEAR"
#define GRAND_MODUS_CLIMATE_FAN_ACTIVE_NAME "FAN_ACTIVE"
#define GRAND_MODUS_CLIMATE_AIR_CONDITIONING_NAME "AIR_CONDITIONING"
#define GRAND_MODUS_CLIMATE_REAR_DEFROSTER_NAME "REAR_DEFROSTER"
#define GRAND_MODUS_BRAKES_PARKING_BRAKE_NAME "PARKING_BRAKE"
#define GRAND_MODUS_LIGHTS_AND_DOORS_TRUNK_NAME "TRUNK"
#define GRAND_MODUS_LIGHTS_AND_DOORS_DOOR_REAR_RIGHT_NAME "DOOR_REAR_RIGHT"
#define GRAND_MODUS_LIGHTS_AND_DOORS_DOOR_REAR_LEFT_NAME "DOOR_REAR_LEFT"
#define GRAND_MODUS_LIGHTS_AND_DOORS_DOOR_PASSENGER_NAME "DOOR_PASSENGER"
#define GRAND_MODUS_LIGHTS_AND_DOORS_DOOR_DRIVER_NAME "DOOR_DRIVER"
#define GRAND_MODUS_LIGHTS_AND_DOORS_PARKING_LIGHTS_NAME "PARKING_LIGHTS"
#define GRAND_MODUS_LIGHTS_AND_DOORS_LOW_BEAMS_NAME "LOW_BEAMS"
#define GRAND_MODUS_LIGHTS_AND_DOORS_TURN_SIGNAL_RIGHT_NAME "TURN_SIGNAL_RIGHT"
#define GRAND_MODUS_LIGHTS_AND_DOORS_TURN_SIGNAL_LEFT_NAME "TURN_SIGNAL_LEFT"
#define GRAND_MODUS_LIGHTS_AND_DOORS_HIGH_BEAMS_NAME "HIGH_BEAMS"
#define GRAND_MODUS_LIGHTS_AND_DOORS_FRONT_FOG_LIGHTS_NAME "FRONT_FOG_LIGHTS"
#define GRAND_MODUS_LIGHTS_AND_DOORS_REAR_FOG_LIGHT_NAME "REAR_FOG_LIGHT"
#define GRAND_MODUS_SAFETY_SEATBELT_UNFASTENED_NAME "SEATBELT_UNFASTENED"

/**
 * Signals in message ENGINE.
 *
 * All signal values are as on the CAN bus.
 */
struct grand_modus_engine_t {
  /**
   * Range: 0..48000 (0..6000 RPM)
   * Scale: 0.125
   * Offset: 0
   */
  uint16_t engine_rpm;
};

/**
 * Signals in message GEARBOX.
 *
 * All signal values are as on the CAN bus.
 */
struct grand_modus_gearbox_t {
  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t reverse_gear;
};

/**
 * Signals in message CLIMATE.
 *
 * All signal values are as on the CAN bus.
 */
struct grand_modus_climate_t {
  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t fan_active;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t air_conditioning;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t rear_defroster;
};

/**
 * Signals in message BRAKES.
 *
 * All signal values are as on the CAN bus.
 */
struct grand_modus_brakes_t {
  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t parking_brake;
};

/**
 * Signals in message LIGHTS_AND_DOORS.
 *
 * All signal values are as on the CAN bus.
 */
struct grand_modus_lights_and_doors_t {
  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t trunk;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t door_rear_right;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t door_rear_left;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t door_passenger;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t door_driver;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t parking_lights;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t low_beams;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t turn_signal_right;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t turn_signal_left;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t high_beams;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t front_fog_lights;

  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t rear_fog_light;
};

/**
 * Signals in message SAFETY.
 *
 * All signal values are as on the CAN bus.
 */
struct grand_modus_safety_t {
  /**
   * Range: 0..1 (0..1 -)
   * Scale: 1
   * Offset: 0
   */
  uint8_t seatbelt_unfastened;
};

/**
 * Pack message ENGINE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int grand_modus_engine_pack(uint8_t *dst_p,
                            const struct grand_modus_engine_t *src_p,
                            size_t size);

/**
 * Unpack message ENGINE.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int grand_modus_engine_unpack(struct grand_modus_engine_t *dst_p,
                              const uint8_t *src_p, size_t size);

/**
 * Init message fields to default values from ENGINE.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int grand_modus_engine_init(struct grand_modus_engine_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t grand_modus_engine_engine_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_engine_engine_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_engine_engine_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_engine_engine_rpm_is_in_phys_range(double value);

/**
 * Pack message GEARBOX.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int grand_modus_gearbox_pack(uint8_t *dst_p,
                             const struct grand_modus_gearbox_t *src_p,
                             size_t size);

/**
 * Unpack message GEARBOX.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int grand_modus_gearbox_unpack(struct grand_modus_gearbox_t *dst_p,
                               const uint8_t *src_p, size_t size);

/**
 * Init message fields to default values from GEARBOX.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int grand_modus_gearbox_init(struct grand_modus_gearbox_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_gearbox_reverse_gear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_gearbox_reverse_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_gearbox_reverse_gear_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_gearbox_reverse_gear_is_in_phys_range(double value);

/**
 * Pack message CLIMATE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int grand_modus_climate_pack(uint8_t *dst_p,
                             const struct grand_modus_climate_t *src_p,
                             size_t size);

/**
 * Unpack message CLIMATE.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int grand_modus_climate_unpack(struct grand_modus_climate_t *dst_p,
                               const uint8_t *src_p, size_t size);

/**
 * Init message fields to default values from CLIMATE.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int grand_modus_climate_init(struct grand_modus_climate_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_climate_fan_active_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_climate_fan_active_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_climate_fan_active_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_climate_fan_active_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_climate_air_conditioning_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_climate_air_conditioning_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_climate_air_conditioning_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_climate_air_conditioning_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_climate_rear_defroster_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_climate_rear_defroster_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_climate_rear_defroster_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_climate_rear_defroster_is_in_phys_range(double value);

/**
 * Pack message BRAKES.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int grand_modus_brakes_pack(uint8_t *dst_p,
                            const struct grand_modus_brakes_t *src_p,
                            size_t size);

/**
 * Unpack message BRAKES.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int grand_modus_brakes_unpack(struct grand_modus_brakes_t *dst_p,
                              const uint8_t *src_p, size_t size);

/**
 * Init message fields to default values from BRAKES.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int grand_modus_brakes_init(struct grand_modus_brakes_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_brakes_parking_brake_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_brakes_parking_brake_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_brakes_parking_brake_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_brakes_parking_brake_is_in_phys_range(double value);

/**
 * Pack message LIGHTS_AND_DOORS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int grand_modus_lights_and_doors_pack(
    uint8_t *dst_p, const struct grand_modus_lights_and_doors_t *src_p,
    size_t size);

/**
 * Unpack message LIGHTS_AND_DOORS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int grand_modus_lights_and_doors_unpack(
    struct grand_modus_lights_and_doors_t *dst_p, const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LIGHTS_AND_DOORS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int grand_modus_lights_and_doors_init(
    struct grand_modus_lights_and_doors_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_trunk_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_trunk_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_trunk_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_trunk_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_door_rear_right_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_door_rear_right_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_rear_right_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_rear_right_is_in_phys_range(
    double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_door_rear_left_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_door_rear_left_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_rear_left_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_rear_left_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_door_passenger_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_door_passenger_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_passenger_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_passenger_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_door_driver_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_door_driver_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_driver_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_door_driver_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_parking_lights_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_parking_lights_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_parking_lights_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_parking_lights_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_low_beams_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_low_beams_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_low_beams_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_low_beams_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_turn_signal_right_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_turn_signal_right_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_turn_signal_right_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_turn_signal_right_is_in_phys_range(
    double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_turn_signal_left_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_turn_signal_left_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_turn_signal_left_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_turn_signal_left_is_in_phys_range(
    double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_high_beams_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_high_beams_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_high_beams_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_high_beams_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_front_fog_lights_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_front_fog_lights_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_front_fog_lights_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_front_fog_lights_is_in_phys_range(
    double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_lights_and_doors_rear_fog_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_lights_and_doors_rear_fog_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_rear_fog_light_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_lights_and_doors_rear_fog_light_is_in_phys_range(double value);

/**
 * Pack message SAFETY.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int grand_modus_safety_pack(uint8_t *dst_p,
                            const struct grand_modus_safety_t *src_p,
                            size_t size);

/**
 * Unpack message SAFETY.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int grand_modus_safety_unpack(struct grand_modus_safety_t *dst_p,
                              const uint8_t *src_p, size_t size);

/**
 * Init message fields to default values from SAFETY.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int grand_modus_safety_init(struct grand_modus_safety_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t grand_modus_safety_seatbelt_unfastened_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double grand_modus_safety_seatbelt_unfastened_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_safety_seatbelt_unfastened_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool grand_modus_safety_seatbelt_unfastened_is_in_phys_range(double value);

#ifdef __cplusplus
}
#endif

#endif
