/**
 * @file grand_modus.c
 *
 * @brief This source file was generated by cantools version 41.4.1 Mon Jun  8
 * 17:36:24 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "grand_modus.h"

static inline uint8_t pack_left_shift_u8(uint8_t value, uint8_t shift,
                                         uint8_t mask) {
  return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(uint16_t value, uint8_t shift,
                                          uint8_t mask) {
  return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(uint16_t value, uint8_t shift,
                                           uint8_t mask) {
  return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(uint8_t value, uint8_t shift,
                                             uint8_t mask) {
  return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(uint8_t value, uint8_t shift,
                                            uint8_t mask) {
  return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(uint8_t value, uint8_t shift,
                                              uint8_t mask) {
  return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int grand_modus_engine_pack(uint8_t *dst_p,
                            const struct grand_modus_engine_t *src_p,
                            size_t size) {
  if (size < 8u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 8);

  dst_p[0] |= pack_right_shift_u16(src_p->engine_rpm, 8u, 0xffu);
  dst_p[1] |= pack_left_shift_u16(src_p->engine_rpm, 0u, 0xffu);
  dst_p[7] |= pack_left_shift_u8(src_p->vehicle_speed, 0u, 0xffu);

  return (8);
}

int grand_modus_engine_unpack(struct grand_modus_engine_t *dst_p,
                              const uint8_t *src_p, size_t size) {
  if (size < 8u) {
    return (-EINVAL);
  }

  dst_p->engine_rpm = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
  dst_p->engine_rpm |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
  dst_p->vehicle_speed = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

  return (0);
}

int grand_modus_engine_init(struct grand_modus_engine_t *msg_p) {
  if (msg_p == NULL)
    return -1;

  memset(msg_p, 0, sizeof(struct grand_modus_engine_t));

  return 0;
}

uint16_t grand_modus_engine_engine_rpm_encode(double value) {
  return (uint16_t)(value / 0.125);
}

double grand_modus_engine_engine_rpm_decode(uint16_t value) {
  return ((double)value * 0.125);
}

bool grand_modus_engine_engine_rpm_is_in_range(uint16_t value) {
  return (value <= 48000u);
}

bool grand_modus_engine_engine_rpm_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 6000.0));
}

uint8_t grand_modus_engine_vehicle_speed_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_engine_vehicle_speed_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_engine_vehicle_speed_is_in_range(uint8_t value) {
  (void)value;

  return (true);
}

bool grand_modus_engine_vehicle_speed_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 255.0));
}

int grand_modus_gearbox_pack(uint8_t *dst_p,
                             const struct grand_modus_gearbox_t *src_p,
                             size_t size) {
  if (size < 6u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 6);

  dst_p[1] |= pack_left_shift_u8(src_p->reverse_gear, 6u, 0x40u);

  return (6);
}

int grand_modus_gearbox_unpack(struct grand_modus_gearbox_t *dst_p,
                               const uint8_t *src_p, size_t size) {
  if (size < 6u) {
    return (-EINVAL);
  }

  dst_p->reverse_gear = unpack_right_shift_u8(src_p[1], 6u, 0x40u);

  return (0);
}

int grand_modus_gearbox_init(struct grand_modus_gearbox_t *msg_p) {
  if (msg_p == NULL)
    return -1;

  memset(msg_p, 0, sizeof(struct grand_modus_gearbox_t));

  return 0;
}

uint8_t grand_modus_gearbox_reverse_gear_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_gearbox_reverse_gear_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_gearbox_reverse_gear_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_gearbox_reverse_gear_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

int grand_modus_climate_pack(uint8_t *dst_p,
                             const struct grand_modus_climate_t *src_p,
                             size_t size) {
  if (size < 3u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 3);

  dst_p[1] |= pack_left_shift_u8(src_p->fan_active, 5u, 0x20u);
  dst_p[1] |= pack_left_shift_u8(src_p->air_conditioning, 4u, 0x10u);
  dst_p[1] |= pack_left_shift_u8(src_p->rear_defroster, 3u, 0x08u);

  return (3);
}

int grand_modus_climate_unpack(struct grand_modus_climate_t *dst_p,
                               const uint8_t *src_p, size_t size) {
  if (size < 3u) {
    return (-EINVAL);
  }

  dst_p->fan_active = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
  dst_p->air_conditioning = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
  dst_p->rear_defroster = unpack_right_shift_u8(src_p[1], 3u, 0x08u);

  return (0);
}

int grand_modus_climate_init(struct grand_modus_climate_t *msg_p) {
  if (msg_p == NULL)
    return -1;

  memset(msg_p, 0, sizeof(struct grand_modus_climate_t));

  return 0;
}

uint8_t grand_modus_climate_fan_active_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_climate_fan_active_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_climate_fan_active_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_climate_fan_active_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_climate_air_conditioning_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_climate_air_conditioning_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_climate_air_conditioning_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_climate_air_conditioning_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_climate_rear_defroster_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_climate_rear_defroster_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_climate_rear_defroster_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_climate_rear_defroster_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

int grand_modus_brakes_pack(uint8_t *dst_p,
                            const struct grand_modus_brakes_t *src_p,
                            size_t size) {
  if (size < 8u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 8);

  dst_p[0] |= pack_left_shift_u8(src_p->parking_brake, 2u, 0x04u);

  return (8);
}

int grand_modus_brakes_unpack(struct grand_modus_brakes_t *dst_p,
                              const uint8_t *src_p, size_t size) {
  if (size < 8u) {
    return (-EINVAL);
  }

  dst_p->parking_brake = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

  return (0);
}

int grand_modus_brakes_init(struct grand_modus_brakes_t *msg_p) {
  if (msg_p == NULL)
    return -1;

  memset(msg_p, 0, sizeof(struct grand_modus_brakes_t));

  return 0;
}

uint8_t grand_modus_brakes_parking_brake_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_brakes_parking_brake_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_brakes_parking_brake_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_brakes_parking_brake_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

int grand_modus_lights_and_doors_pack(
    uint8_t *dst_p, const struct grand_modus_lights_and_doors_t *src_p,
    size_t size) {
  if (size < 8u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 8);

  dst_p[0] |= pack_left_shift_u8(src_p->trunk, 7u, 0x80u);
  dst_p[0] |= pack_left_shift_u8(src_p->door_rear_right, 6u, 0x40u);
  dst_p[0] |= pack_left_shift_u8(src_p->door_rear_left, 5u, 0x20u);
  dst_p[0] |= pack_left_shift_u8(src_p->door_passenger, 4u, 0x10u);
  dst_p[0] |= pack_left_shift_u8(src_p->door_driver, 3u, 0x08u);
  dst_p[0] |= pack_left_shift_u8(src_p->parking_lights, 2u, 0x04u);
  dst_p[0] |= pack_left_shift_u8(src_p->low_beams, 1u, 0x02u);
  dst_p[1] |= pack_left_shift_u8(src_p->turn_signal_right, 6u, 0x40u);
  dst_p[1] |= pack_left_shift_u8(src_p->turn_signal_left, 5u, 0x20u);
  dst_p[1] |= pack_left_shift_u8(src_p->high_beams, 3u, 0x08u);
  dst_p[1] |= pack_left_shift_u8(src_p->front_fog_lights, 0u, 0x01u);
  dst_p[2] |= pack_left_shift_u8(src_p->rear_fog_light, 2u, 0x04u);

  return (8);
}

int grand_modus_lights_and_doors_unpack(
    struct grand_modus_lights_and_doors_t *dst_p, const uint8_t *src_p,
    size_t size) {
  if (size < 8u) {
    return (-EINVAL);
  }

  dst_p->trunk = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
  dst_p->door_rear_right = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
  dst_p->door_rear_left = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
  dst_p->door_passenger = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
  dst_p->door_driver = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
  dst_p->parking_lights = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
  dst_p->low_beams = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
  dst_p->turn_signal_right = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
  dst_p->turn_signal_left = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
  dst_p->high_beams = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
  dst_p->front_fog_lights = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
  dst_p->rear_fog_light = unpack_right_shift_u8(src_p[2], 2u, 0x04u);

  return (0);
}

int grand_modus_lights_and_doors_init(
    struct grand_modus_lights_and_doors_t *msg_p) {
  if (msg_p == NULL)
    return -1;

  memset(msg_p, 0, sizeof(struct grand_modus_lights_and_doors_t));

  return 0;
}

uint8_t grand_modus_lights_and_doors_trunk_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_trunk_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_trunk_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_trunk_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_door_rear_right_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_door_rear_right_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_door_rear_right_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_door_rear_right_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_door_rear_left_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_door_rear_left_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_door_rear_left_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_door_rear_left_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_door_passenger_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_door_passenger_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_door_passenger_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_door_passenger_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_door_driver_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_door_driver_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_door_driver_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_door_driver_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_parking_lights_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_parking_lights_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_parking_lights_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_parking_lights_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_low_beams_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_low_beams_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_low_beams_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_low_beams_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_turn_signal_right_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_turn_signal_right_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_turn_signal_right_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_turn_signal_right_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_turn_signal_left_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_turn_signal_left_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_turn_signal_left_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_turn_signal_left_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_high_beams_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_high_beams_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_high_beams_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_high_beams_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_front_fog_lights_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_front_fog_lights_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_front_fog_lights_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_front_fog_lights_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

uint8_t grand_modus_lights_and_doors_rear_fog_light_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_lights_and_doors_rear_fog_light_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_lights_and_doors_rear_fog_light_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_lights_and_doors_rear_fog_light_is_in_phys_range(
    double value) {
  return ((value >= 0.0) && (value <= 1.0));
}

int grand_modus_safety_pack(uint8_t *dst_p,
                            const struct grand_modus_safety_t *src_p,
                            size_t size) {
  if (size < 2u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 2);

  dst_p[1] |= pack_left_shift_u8(src_p->seatbelt_unfastened, 0u, 0x01u);

  return (2);
}

int grand_modus_safety_unpack(struct grand_modus_safety_t *dst_p,
                              const uint8_t *src_p, size_t size) {
  if (size < 2u) {
    return (-EINVAL);
  }

  dst_p->seatbelt_unfastened = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

  return (0);
}

int grand_modus_safety_init(struct grand_modus_safety_t *msg_p) {
  if (msg_p == NULL)
    return -1;

  memset(msg_p, 0, sizeof(struct grand_modus_safety_t));

  return 0;
}

uint8_t grand_modus_safety_seatbelt_unfastened_encode(double value) {
  return (uint8_t)(value);
}

double grand_modus_safety_seatbelt_unfastened_decode(uint8_t value) {
  return ((double)value);
}

bool grand_modus_safety_seatbelt_unfastened_is_in_range(uint8_t value) {
  return (value <= 1u);
}

bool grand_modus_safety_seatbelt_unfastened_is_in_phys_range(double value) {
  return ((value >= 0.0) && (value <= 1.0));
}
